/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminTable: typeof import('./components/panel/admin/AdminTable.vue')['default']
    AuthorCard: typeof import('./components/frontend/author/AuthorCard.vue')['default']
    Book: typeof import('./components/panel/idare/Book.vue')['default']
    BookCard: typeof import('./components/frontend/book/BookCard.vue')['default']
    CommentList: typeof import('./components/frontend/bookDetail/commentList.vue')['default']
    ConfirmDialog: typeof import('./components/common/ConfirmDialog.vue')['default']
    DeleteAndUpdate: typeof import('./components/shared/Table/DeleteAndUpdate.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    EmptyStateCard: typeof import('./components/shared/EmptyStateCard.vue')['default']
    EndOfListMessage: typeof import('./components/common/EndOfListMessage.vue')['default']
    ErrorState: typeof import('./components/common/ErrorState.vue')['default']
    Footer: typeof import('./components/shared/Footer.vue')['default']
    FriendActionButtons: typeof import('./components/profile/FriendActionButtons.vue')['default']
    FriendCard: typeof import('./components/friends/FriendCard.vue')['default']
    FriendRequestCard: typeof import('./components/friends/FriendRequestCard.vue')['default']
    FriendshipCard: typeof import('./components/friends/FriendshipCard.vue')['default']
    GoToButtons: typeof import('./components/frontend/poems/GoToButtons.vue')['default']
    HomepageTable: typeof import('./components/panel/admin/HomepageTable.vue')['default']
    LazyLoadingIndicator: typeof import('./components/common/LazyLoadingIndicator.vue')['default']
    LoadingState: typeof import('./components/common/LoadingState.vue')['default']
    LoadingStateCard: typeof import('./components/shared/LoadingStateCard.vue')['default']
    LogTable: typeof import('./components/panel/log/LogTable.vue')['default']
    MihrimahCardTable: typeof import('./components/panel/admin/MihrimahCardTable.vue')['default']
    NoComment: typeof import('./components/frontend/bookDetail/noComment.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    PoemCard: typeof import('./components/frontend/poem/PoemCard.vue')['default']
    PoemTable: typeof import('./components/panel/poem/PoemTable.vue')['default']
    PrivacyToggle: typeof import('./components/profile/PrivacyToggle.vue')['default']
    ProfileAvatar: typeof import('./components/profile/ProfileAvatar.vue')['default']
    ProfileItemsDialog: typeof import('./components/profile/ProfileItemsDialog.vue')['default']
    ProfileStats: typeof import('./components/profile/ProfileStats.vue')['default']
    ReminderTable: typeof import('./components/panel/reminder/ReminderTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchSection: typeof import('./components/common/SearchSection.vue')['default']
    SentRequestCard: typeof import('./components/friends/SentRequestCard.vue')['default']
    SnackbarNotification: typeof import('./components/common/SnackbarNotification.vue')['default']
    StatCard: typeof import('./components/common/StatCard.vue')['default']
    Table: typeof import('./components/shared/Table/Table.vue')['default']
    TitleCard: typeof import('./components/shared/TitleCard.vue')['default']
  }
}
