/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Management/AdminManagement': RouteRecordInfo<'/Management/AdminManagement', '/Management/AdminManagement', Record<never, never>, Record<never, never>>,
    '/Management/AuthorManagement': RouteRecordInfo<'/Management/AuthorManagement', '/Management/AuthorManagement', Record<never, never>, Record<never, never>>,
    '/Management/BookManagement': RouteRecordInfo<'/Management/BookManagement', '/Management/BookManagement', Record<never, never>, Record<never, never>>,
    '/Management/HomepageManagement': RouteRecordInfo<'/Management/HomepageManagement', '/Management/HomepageManagement', Record<never, never>, Record<never, never>>,
    '/Management/LogManagement': RouteRecordInfo<'/Management/LogManagement', '/Management/LogManagement', Record<never, never>, Record<never, never>>,
    '/Management/MihrimahCardManagement': RouteRecordInfo<'/Management/MihrimahCardManagement', '/Management/MihrimahCardManagement', Record<never, never>, Record<never, never>>,
    '/Management/PoemManagement': RouteRecordInfo<'/Management/PoemManagement', '/Management/PoemManagement', Record<never, never>, Record<never, never>>,
    '/Management/reminderManagement': RouteRecordInfo<'/Management/reminderManagement', '/Management/reminderManagement', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/RegisterUser': RouteRecordInfo<'/RegisterUser', '/RegisterUser', Record<never, never>, Record<never, never>>,
    '/User/AuthorDetail': RouteRecordInfo<'/User/AuthorDetail', '/User/AuthorDetail', Record<never, never>, Record<never, never>>,
    '/User/Authors': RouteRecordInfo<'/User/Authors', '/User/Authors', Record<never, never>, Record<never, never>>,
    '/User/Book': RouteRecordInfo<'/User/Book', '/User/Book', Record<never, never>, Record<never, never>>,
    '/User/Book/BookDetail': RouteRecordInfo<'/User/Book/BookDetail', '/User/Book/BookDetail', Record<never, never>, Record<never, never>>,
    '/User/Book/BookList': RouteRecordInfo<'/User/Book/BookList', '/User/Book/BookList', Record<never, never>, Record<never, never>>,
    '/User/Bookmark': RouteRecordInfo<'/User/Bookmark', '/User/Bookmark', Record<never, never>, Record<never, never>>,
    '/User/Friends': RouteRecordInfo<'/User/Friends', '/User/Friends', Record<never, never>, Record<never, never>>,
    '/User/Home': RouteRecordInfo<'/User/Home', '/User/Home', Record<never, never>, Record<never, never>>,
    '/User/LatestPoems': RouteRecordInfo<'/User/LatestPoems', '/User/LatestPoems', Record<never, never>, Record<never, never>>,
    '/User/LikedPoems': RouteRecordInfo<'/User/LikedPoems', '/User/LikedPoems', Record<never, never>, Record<never, never>>,
    '/User/Login': RouteRecordInfo<'/User/Login', '/User/Login', Record<never, never>, Record<never, never>>,
    '/User/NotReadsBooks': RouteRecordInfo<'/User/NotReadsBooks', '/User/NotReadsBooks', Record<never, never>, Record<never, never>>,
    '/User/Panel': RouteRecordInfo<'/User/Panel', '/User/Panel', Record<never, never>, Record<never, never>>,
    '/User/Poem': RouteRecordInfo<'/User/Poem', '/User/Poem', Record<never, never>, Record<never, never>>,
    '/User/Poems': RouteRecordInfo<'/User/Poems', '/User/Poems', Record<never, never>, Record<never, never>>,
    '/User/PopularPoems': RouteRecordInfo<'/User/PopularPoems', '/User/PopularPoems', Record<never, never>, Record<never, never>>,
    '/User/ReadsBooks': RouteRecordInfo<'/User/ReadsBooks', '/User/ReadsBooks', Record<never, never>, Record<never, never>>,
    '/User/Reminder': RouteRecordInfo<'/User/Reminder', '/User/Reminder', Record<never, never>, Record<never, never>>,
    '/User/UserProfile': RouteRecordInfo<'/User/UserProfile', '/User/UserProfile', Record<never, never>, Record<never, never>>,
  }
}
